#!/usr/bin/env bash

python scripts/run_pipeline.py --affine-path /data/exaSPIM_613814_2023-04-15_13-02-26_fusion_2023-04-26_15-08-00/CCF_Atlas_Registration10/affine_transforms.mat --slicer-transform "/data/exaSPIM_CCF_Completed/613814-completed/Displacement Field_613814.nrrd" --swc-dir /data/613814_cells_medulla_refined/final-world --image-path /data/exaSPIM_613814_2023-04-15_13-02-26_fusion_2023-04-26_15-08-00/fused.zarr --output-dir /results --output-json --transform-res 10 10 10 --input-res 0.31640625 0.31640625 0.421875 --swc-scale 0.748 0.748 1.0 
