#!/usr/bin/env bash

python scripts/run_pipeline.py --affine-path /data/data/exaSPIM_658735_2023-08-15_16-13-50_fusion_2023-09-01/CCF_Atlas_Registration10/658735_scaled.mat --slicer-transform "/data/exaSPIM_CCF_Completed/658735-completed/Displacement Field_658735.nrrd" --swc-dir /data/658735_cells_medulla_refined/final-world --image-path /data/exaSPIM_658735_2023-08-15_16-13-50_fusion_2023-09-01/fused.zarr --output-dir /results --output-json --transform-res 10 10 10 --input-res 0.31640625 0.31640625 0.421875 --swc-scale 0.748 0.748 1.0 
