environment_version: 1
credentials:
- type: aws
  id: YXgaMDj47f3fte2a
  description: AWS Assumable Role - aind-codeocean-power-user
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  region: AWS_DEFAULT_REGION
